spring:
  sql:
    init:
      schema-locations: classpath:/sql/schema.sql
      mode: always

  datasource:
    url: jdbc:postgresql://localhost:5432/contactdb
    username: developer
    password: developer
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: contact-db-pool
      maximum-pool-size: 10

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8080
